import 'package:cloud_firestore/cloud_firestore.dart';

class CategoriesService {
  static final _firestore = FirebaseFirestore.instance;
  static const _version = 7;

  static Future<void> seedIfNeeded() async {
    try {
      final meta = await _firestore.collection('meta').doc('categories').get();

      if (!meta.exists || meta.data()?['version'] != _version) {
        print('Seeding categories...');
        await _seedCategories();
        await _firestore.collection('meta').doc('categories').set({
          'version': _version,
          'updatedAt': DateTime.now().toIso8601String(),
        });
        print('Categories seeded successfully!');
      } else {
        print('Categories already up to date.');
      }
    } catch (e) {
      print('Seed error: $e');
    }
  }

  static Future<void> _seedCategories() async {
    final existing = await _firestore.collection('categories').get();
    for (final doc in existing.docs) {
      await doc.reference.delete();
    }

    final batch = _firestore.batch();
    for (final category in _categories) {
      final ref = _firestore
          .collection('categories')
          .doc(category['id'] as String);
      batch.set(ref, category);
    }
    await batch.commit();
  }

  static Future<List<Map<String, dynamic>>> getAll() async {
    final snapshot = await _firestore
        .collection('categories')
        .orderBy('group')
        .orderBy('order')
        .get();
    return snapshot.docs.map((doc) => doc.data()).toList();
  }

  static Future<List<Map<String, dynamic>>> getByGroup(String group) async {
    final snapshot = await _firestore
        .collection('categories')
        .where('group', isEqualTo: group)
        .orderBy('order')
        .get();
    return snapshot.docs.map((doc) => doc.data()).toList();
  }

  static const List<Map<String, dynamic>> _categories = [
    // Automotive
    {
      'id': 'car_dealer',
      'label': 'Car Dealer',
      'group': 'Automotive',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'car_rental',
      'label': 'Car Rental',
      'group': 'Automotive',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'car_repair',
      'label': 'Car Repair',
      'group': 'Automotive',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'car_wash',
      'label': 'Car Wash',
      'group': 'Automotive',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'ebike_charging_station',
      'label': 'E-Bike Charging Station',
      'group': 'Automotive',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'electric_vehicle_charging_station',
      'label': 'EV Charging Station',
      'group': 'Automotive',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'gas_station',
      'label': 'Gas Station',
      'group': 'Automotive',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'parking',
      'label': 'Parking',
      'group': 'Automotive',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'parking_garage',
      'label': 'Parking Garage',
      'group': 'Automotive',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'parking_lot',
      'label': 'Parking Lot',
      'group': 'Automotive',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'rest_stop',
      'label': 'Rest Stop',
      'group': 'Automotive',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'tire_shop',
      'label': 'Tire Shop',
      'group': 'Automotive',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'truck_dealer',
      'label': 'Truck Dealer',
      'group': 'Automotive',
      'table': 'A',
      'order': 13,
    },

    // Business
    {
      'id': 'business_center',
      'label': 'Business Center',
      'group': 'Business',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'corporate_office',
      'label': 'Corporate Office',
      'group': 'Business',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'coworking_space',
      'label': 'Coworking Space',
      'group': 'Business',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'farm',
      'label': 'Farm',
      'group': 'Business',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'manufacturer',
      'label': 'Manufacturer',
      'group': 'Business',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'ranch',
      'label': 'Ranch',
      'group': 'Business',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'supplier',
      'label': 'Supplier',
      'group': 'Business',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'television_studio',
      'label': 'Television Studio',
      'group': 'Business',
      'table': 'A',
      'order': 8,
    },

    // Culture
    {
      'id': 'art_gallery',
      'label': 'Art Gallery',
      'group': 'Culture',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'art_museum',
      'label': 'Art Museum',
      'group': 'Culture',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'art_studio',
      'label': 'Art Studio',
      'group': 'Culture',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'auditorium',
      'label': 'Auditorium',
      'group': 'Culture',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'castle',
      'label': 'Castle',
      'group': 'Culture',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'cultural_landmark',
      'label': 'Cultural Landmark',
      'group': 'Culture',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'fountain',
      'label': 'Fountain',
      'group': 'Culture',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'historical_place',
      'label': 'Historical Place',
      'group': 'Culture',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'history_museum',
      'label': 'History Museum',
      'group': 'Culture',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'monument',
      'label': 'Monument',
      'group': 'Culture',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'museum',
      'label': 'Museum',
      'group': 'Culture',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'performing_arts_theater',
      'label': 'Performing Arts Theater',
      'group': 'Culture',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'sculpture',
      'label': 'Sculpture',
      'group': 'Culture',
      'table': 'A',
      'order': 13,
    },

    // Education
    {
      'id': 'academic_department',
      'label': 'Academic Department',
      'group': 'Education',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'educational_institution',
      'label': 'Educational Institution',
      'group': 'Education',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'library',
      'label': 'Library',
      'group': 'Education',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'preschool',
      'label': 'Preschool',
      'group': 'Education',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'primary_school',
      'label': 'Primary School',
      'group': 'Education',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'research_institute',
      'label': 'Research Institute',
      'group': 'Education',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'school',
      'label': 'School',
      'group': 'Education',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'secondary_school',
      'label': 'Secondary School',
      'group': 'Education',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'university',
      'label': 'University',
      'group': 'Education',
      'table': 'A',
      'order': 9,
    },

    // Facilities
    {
      'id': 'public_bath',
      'label': 'Public Bath',
      'group': 'Facilities',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'public_bathroom',
      'label': 'Public Bathroom',
      'group': 'Facilities',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'stable',
      'label': 'Stable',
      'group': 'Facilities',
      'table': 'A',
      'order': 3,
    },

    // Finance
    {
      'id': 'accounting',
      'label': 'Accounting',
      'group': 'Finance',
      'table': 'A',
      'order': 1,
    },
    {'id': 'atm', 'label': 'ATM', 'group': 'Finance', 'table': 'A', 'order': 2},
    {
      'id': 'bank',
      'label': 'Bank',
      'group': 'Finance',
      'table': 'A',
      'order': 3,
    },

    // Food & Drink
    {
      'id': 'acai_shop',
      'label': 'Acai Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'afghani_restaurant',
      'label': 'Afghani Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'african_restaurant',
      'label': 'African Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'american_restaurant',
      'label': 'American Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'argentinian_restaurant',
      'label': 'Argentinian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'asian_fusion_restaurant',
      'label': 'Asian Fusion Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'asian_restaurant',
      'label': 'Asian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'australian_restaurant',
      'label': 'Australian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'austrian_restaurant',
      'label': 'Austrian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'bagel_shop',
      'label': 'Bagel Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'bakery',
      'label': 'Bakery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'bangladeshi_restaurant',
      'label': 'Bangladeshi Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'bar',
      'label': 'Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'bar_and_grill',
      'label': 'Bar & Grill',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'barbecue_restaurant',
      'label': 'Barbecue Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'basque_restaurant',
      'label': 'Basque Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'bavarian_restaurant',
      'label': 'Bavarian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'beer_garden',
      'label': 'Beer Garden',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 18,
    },
    {
      'id': 'belgian_restaurant',
      'label': 'Belgian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 19,
    },
    {
      'id': 'bistro',
      'label': 'Bistro',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 20,
    },
    {
      'id': 'brazilian_restaurant',
      'label': 'Brazilian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 21,
    },
    {
      'id': 'breakfast_restaurant',
      'label': 'Breakfast Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 22,
    },
    {
      'id': 'brewery',
      'label': 'Brewery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 23,
    },
    {
      'id': 'brewpub',
      'label': 'Brewpub',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 24,
    },
    {
      'id': 'british_restaurant',
      'label': 'British Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 25,
    },
    {
      'id': 'brunch_restaurant',
      'label': 'Brunch Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 26,
    },
    {
      'id': 'buffet_restaurant',
      'label': 'Buffet Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 27,
    },
    {
      'id': 'burmese_restaurant',
      'label': 'Burmese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 28,
    },
    {
      'id': 'burrito_restaurant',
      'label': 'Burrito Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 29,
    },
    {
      'id': 'cafe',
      'label': 'Cafe',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 30,
    },
    {
      'id': 'cafeteria',
      'label': 'Cafeteria',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 31,
    },
    {
      'id': 'cajun_restaurant',
      'label': 'Cajun Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 32,
    },
    {
      'id': 'cake_shop',
      'label': 'Cake Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 33,
    },
    {
      'id': 'californian_restaurant',
      'label': 'Californian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 34,
    },
    {
      'id': 'cambodian_restaurant',
      'label': 'Cambodian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 35,
    },
    {
      'id': 'candy_store',
      'label': 'Candy Store',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 36,
    },
    {
      'id': 'cantonese_restaurant',
      'label': 'Cantonese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 37,
    },
    {
      'id': 'caribbean_restaurant',
      'label': 'Caribbean Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 38,
    },
    {
      'id': 'cat_cafe',
      'label': 'Cat Cafe',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 39,
    },
    {
      'id': 'chicken_restaurant',
      'label': 'Chicken Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 40,
    },
    {
      'id': 'chicken_wings_restaurant',
      'label': 'Chicken Wings Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 41,
    },
    {
      'id': 'chilean_restaurant',
      'label': 'Chilean Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 42,
    },
    {
      'id': 'chinese_noodle_restaurant',
      'label': 'Chinese Noodle Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 43,
    },
    {
      'id': 'chinese_restaurant',
      'label': 'Chinese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 44,
    },
    {
      'id': 'chocolate_factory',
      'label': 'Chocolate Factory',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 45,
    },
    {
      'id': 'chocolate_shop',
      'label': 'Chocolate Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 46,
    },
    {
      'id': 'cocktail_bar',
      'label': 'Cocktail Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 47,
    },
    {
      'id': 'coffee_roastery',
      'label': 'Coffee Roastery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 48,
    },
    {
      'id': 'coffee_shop',
      'label': 'Coffee Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 49,
    },
    {
      'id': 'coffee_stand',
      'label': 'Coffee Stand',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 50,
    },
    {
      'id': 'colombian_restaurant',
      'label': 'Colombian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 51,
    },
    {
      'id': 'confectionery',
      'label': 'Confectionery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 52,
    },
    {
      'id': 'croatian_restaurant',
      'label': 'Croatian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 53,
    },
    {
      'id': 'cuban_restaurant',
      'label': 'Cuban Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 54,
    },
    {
      'id': 'czech_restaurant',
      'label': 'Czech Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 55,
    },
    {
      'id': 'danish_restaurant',
      'label': 'Danish Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 56,
    },
    {
      'id': 'deli',
      'label': 'Deli',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 57,
    },
    {
      'id': 'dessert_restaurant',
      'label': 'Dessert Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 58,
    },
    {
      'id': 'dessert_shop',
      'label': 'Dessert Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 59,
    },
    {
      'id': 'dim_sum_restaurant',
      'label': 'Dim Sum Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 60,
    },
    {
      'id': 'diner',
      'label': 'Diner',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 61,
    },
    {
      'id': 'dog_cafe',
      'label': 'Dog Cafe',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 62,
    },
    {
      'id': 'donut_shop',
      'label': 'Donut Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 63,
    },
    {
      'id': 'dumpling_restaurant',
      'label': 'Dumpling Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 64,
    },
    {
      'id': 'dutch_restaurant',
      'label': 'Dutch Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 65,
    },
    {
      'id': 'eastern_european_restaurant',
      'label': 'Eastern European Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 66,
    },
    {
      'id': 'ethiopian_restaurant',
      'label': 'Ethiopian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 67,
    },
    {
      'id': 'european_restaurant',
      'label': 'European Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 68,
    },
    {
      'id': 'falafel_restaurant',
      'label': 'Falafel Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 69,
    },
    {
      'id': 'family_restaurant',
      'label': 'Family Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 70,
    },
    {
      'id': 'fast_food_restaurant',
      'label': 'Fast Food Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 71,
    },
    {
      'id': 'filipino_restaurant',
      'label': 'Filipino Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 72,
    },
    {
      'id': 'fine_dining_restaurant',
      'label': 'Fine Dining Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 73,
    },
    {
      'id': 'fish_and_chips_restaurant',
      'label': 'Fish & Chips Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 74,
    },
    {
      'id': 'fondue_restaurant',
      'label': 'Fondue Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 75,
    },
    {
      'id': 'food_court',
      'label': 'Food Court',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 76,
    },
    {
      'id': 'french_restaurant',
      'label': 'French Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 77,
    },
    {
      'id': 'fusion_restaurant',
      'label': 'Fusion Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 78,
    },
    {
      'id': 'gastropub',
      'label': 'Gastropub',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 79,
    },
    {
      'id': 'german_restaurant',
      'label': 'German Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 80,
    },
    {
      'id': 'greek_restaurant',
      'label': 'Greek Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 81,
    },
    {
      'id': 'gyro_restaurant',
      'label': 'Gyro Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 82,
    },
    {
      'id': 'halal_restaurant',
      'label': 'Halal Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 83,
    },
    {
      'id': 'hamburger_restaurant',
      'label': 'Hamburger Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 84,
    },
    {
      'id': 'hawaiian_restaurant',
      'label': 'Hawaiian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 85,
    },
    {
      'id': 'hookah_bar',
      'label': 'Hookah Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 86,
    },
    {
      'id': 'hot_dog_restaurant',
      'label': 'Hot Dog Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 87,
    },
    {
      'id': 'hot_dog_stand',
      'label': 'Hot Dog Stand',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 88,
    },
    {
      'id': 'hot_pot_restaurant',
      'label': 'Hot Pot Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 89,
    },
    {
      'id': 'hungarian_restaurant',
      'label': 'Hungarian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 90,
    },
    {
      'id': 'ice_cream_shop',
      'label': 'Ice Cream Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 91,
    },
    {
      'id': 'indian_restaurant',
      'label': 'Indian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 92,
    },
    {
      'id': 'indonesian_restaurant',
      'label': 'Indonesian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 93,
    },
    {
      'id': 'irish_pub',
      'label': 'Irish Pub',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 94,
    },
    {
      'id': 'irish_restaurant',
      'label': 'Irish Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 95,
    },
    {
      'id': 'israeli_restaurant',
      'label': 'Israeli Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 96,
    },
    {
      'id': 'italian_restaurant',
      'label': 'Italian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 97,
    },
    {
      'id': 'japanese_curry_restaurant',
      'label': 'Japanese Curry Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 98,
    },
    {
      'id': 'japanese_izakaya_restaurant',
      'label': 'Japanese Izakaya Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 99,
    },
    {
      'id': 'japanese_restaurant',
      'label': 'Japanese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 100,
    },
    {
      'id': 'juice_shop',
      'label': 'Juice Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 101,
    },
    {
      'id': 'kebab_shop',
      'label': 'Kebab Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 102,
    },
    {
      'id': 'korean_barbecue_restaurant',
      'label': 'Korean Barbecue Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 103,
    },
    {
      'id': 'korean_restaurant',
      'label': 'Korean Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 104,
    },
    {
      'id': 'latin_american_restaurant',
      'label': 'Latin American Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 105,
    },
    {
      'id': 'lebanese_restaurant',
      'label': 'Lebanese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 106,
    },
    {
      'id': 'lounge_bar',
      'label': 'Lounge Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 107,
    },
    {
      'id': 'malaysian_restaurant',
      'label': 'Malaysian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 108,
    },
    {
      'id': 'meal_delivery',
      'label': 'Meal Delivery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 109,
    },
    {
      'id': 'meal_takeaway',
      'label': 'Meal Takeaway',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 110,
    },
    {
      'id': 'mediterranean_restaurant',
      'label': 'Mediterranean Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 111,
    },
    {
      'id': 'mexican_restaurant',
      'label': 'Mexican Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 112,
    },
    {
      'id': 'middle_eastern_restaurant',
      'label': 'Middle Eastern Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 113,
    },
    {
      'id': 'mongolian_barbecue_restaurant',
      'label': 'Mongolian Barbecue Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 114,
    },
    {
      'id': 'moroccan_restaurant',
      'label': 'Moroccan Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 115,
    },
    {
      'id': 'noodle_shop',
      'label': 'Noodle Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 116,
    },
    {
      'id': 'north_indian_restaurant',
      'label': 'North Indian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 117,
    },
    {
      'id': 'oyster_bar_restaurant',
      'label': 'Oyster Bar Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 118,
    },
    {
      'id': 'pakistani_restaurant',
      'label': 'Pakistani Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 119,
    },
    {
      'id': 'pastry_shop',
      'label': 'Pastry Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 120,
    },
    {
      'id': 'persian_restaurant',
      'label': 'Persian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 121,
    },
    {
      'id': 'peruvian_restaurant',
      'label': 'Peruvian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 122,
    },
    {
      'id': 'pizza_delivery',
      'label': 'Pizza Delivery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 123,
    },
    {
      'id': 'pizza_restaurant',
      'label': 'Pizza Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 124,
    },
    {
      'id': 'polish_restaurant',
      'label': 'Polish Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 125,
    },
    {
      'id': 'portuguese_restaurant',
      'label': 'Portuguese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 126,
    },
    {
      'id': 'pub',
      'label': 'Pub',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 127,
    },
    {
      'id': 'ramen_restaurant',
      'label': 'Ramen Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 128,
    },
    {
      'id': 'restaurant',
      'label': 'Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 129,
    },
    {
      'id': 'romanian_restaurant',
      'label': 'Romanian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 130,
    },
    {
      'id': 'russian_restaurant',
      'label': 'Russian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 131,
    },
    {
      'id': 'salad_shop',
      'label': 'Salad Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 132,
    },
    {
      'id': 'sandwich_shop',
      'label': 'Sandwich Shop',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 133,
    },
    {
      'id': 'scandinavian_restaurant',
      'label': 'Scandinavian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 134,
    },
    {
      'id': 'seafood_restaurant',
      'label': 'Seafood Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 135,
    },
    {
      'id': 'shawarma_restaurant',
      'label': 'Shawarma Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 136,
    },
    {
      'id': 'snack_bar',
      'label': 'Snack Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 137,
    },
    {
      'id': 'soul_food_restaurant',
      'label': 'Soul Food Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 138,
    },
    {
      'id': 'soup_restaurant',
      'label': 'Soup Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 139,
    },
    {
      'id': 'south_american_restaurant',
      'label': 'South American Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 140,
    },
    {
      'id': 'south_indian_restaurant',
      'label': 'South Indian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 141,
    },
    {
      'id': 'southwestern_us_restaurant',
      'label': 'Southwestern US Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 142,
    },
    {
      'id': 'spanish_restaurant',
      'label': 'Spanish Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 143,
    },
    {
      'id': 'sports_bar',
      'label': 'Sports Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 144,
    },
    {
      'id': 'sri_lankan_restaurant',
      'label': 'Sri Lankan Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 145,
    },
    {
      'id': 'steak_house',
      'label': 'Steak House',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 146,
    },
    {
      'id': 'sushi_restaurant',
      'label': 'Sushi Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 147,
    },
    {
      'id': 'swiss_restaurant',
      'label': 'Swiss Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 148,
    },
    {
      'id': 'taco_restaurant',
      'label': 'Taco Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 149,
    },
    {
      'id': 'taiwanese_restaurant',
      'label': 'Taiwanese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 150,
    },
    {
      'id': 'tapas_restaurant',
      'label': 'Tapas Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 151,
    },
    {
      'id': 'tea_house',
      'label': 'Tea House',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 152,
    },
    {
      'id': 'tex_mex_restaurant',
      'label': 'Tex-Mex Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 153,
    },
    {
      'id': 'thai_restaurant',
      'label': 'Thai Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 154,
    },
    {
      'id': 'tibetan_restaurant',
      'label': 'Tibetan Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 155,
    },
    {
      'id': 'tonkatsu_restaurant',
      'label': 'Tonkatsu Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 156,
    },
    {
      'id': 'turkish_restaurant',
      'label': 'Turkish Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 157,
    },
    {
      'id': 'ukrainian_restaurant',
      'label': 'Ukrainian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 158,
    },
    {
      'id': 'vegan_restaurant',
      'label': 'Vegan Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 159,
    },
    {
      'id': 'vegetarian_restaurant',
      'label': 'Vegetarian Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 160,
    },
    {
      'id': 'vietnamese_restaurant',
      'label': 'Vietnamese Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 161,
    },
    {
      'id': 'western_restaurant',
      'label': 'Western Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 162,
    },
    {
      'id': 'wine_bar',
      'label': 'Wine Bar',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 163,
    },
    {
      'id': 'winery',
      'label': 'Winery',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 164,
    },
    {
      'id': 'yakiniku_restaurant',
      'label': 'Yakiniku Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 165,
    },
    {
      'id': 'yakitori_restaurant',
      'label': 'Yakitori Restaurant',
      'group': 'Food & Drink',
      'table': 'A',
      'order': 166,
    },

    // Geographical Areas
    {
      'id': 'administrative_area_level_1',
      'label': 'Administrative Area Level 1',
      'group': 'Geographical Areas',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'administrative_area_level_2',
      'label': 'Administrative Area Level 2',
      'group': 'Geographical Areas',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'country',
      'label': 'Country',
      'group': 'Geographical Areas',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'locality',
      'label': 'Locality',
      'group': 'Geographical Areas',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'postal_code',
      'label': 'Postal Code',
      'group': 'Geographical Areas',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'school_district',
      'label': 'School District',
      'group': 'Geographical Areas',
      'table': 'A',
      'order': 6,
    },

    // Government
    {
      'id': 'city_hall',
      'label': 'City Hall',
      'group': 'Government',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'courthouse',
      'label': 'Courthouse',
      'group': 'Government',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'embassy',
      'label': 'Embassy',
      'group': 'Government',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'fire_station',
      'label': 'Fire Station',
      'group': 'Government',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'government_office',
      'label': 'Government Office',
      'group': 'Government',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'local_government_office',
      'label': 'Local Government Office',
      'group': 'Government',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'neighborhood_police_station',
      'label': 'Neighborhood Police Station',
      'group': 'Government',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'police',
      'label': 'Police',
      'group': 'Government',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'post_office',
      'label': 'Post Office',
      'group': 'Government',
      'table': 'A',
      'order': 9,
    },

    // Health & Wellness
    {
      'id': 'chiropractor',
      'label': 'Chiropractor',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'dental_clinic',
      'label': 'Dental Clinic',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'dentist',
      'label': 'Dentist',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'doctor',
      'label': 'Doctor',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'drugstore',
      'label': 'Drugstore',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'general_hospital',
      'label': 'General Hospital',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'hospital',
      'label': 'Hospital',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'massage',
      'label': 'Massage',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'massage_spa',
      'label': 'Massage Spa',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'medical_center',
      'label': 'Medical Center',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'medical_clinic',
      'label': 'Medical Clinic',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'medical_lab',
      'label': 'Medical Lab',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'pharmacy',
      'label': 'Pharmacy',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'physiotherapist',
      'label': 'Physiotherapist',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'sauna',
      'label': 'Sauna',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'skin_care_clinic',
      'label': 'Skin Care Clinic',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'spa',
      'label': 'Spa',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'tanning_studio',
      'label': 'Tanning Studio',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 18,
    },
    {
      'id': 'wellness_center',
      'label': 'Wellness Center',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 19,
    },
    {
      'id': 'yoga_studio',
      'label': 'Yoga Studio',
      'group': 'Health & Wellness',
      'table': 'A',
      'order': 20,
    },

    // Housing
    {
      'id': 'apartment_building',
      'label': 'Apartment Building',
      'group': 'Housing',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'apartment_complex',
      'label': 'Apartment Complex',
      'group': 'Housing',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'condominium_complex',
      'label': 'Condominium Complex',
      'group': 'Housing',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'housing_complex',
      'label': 'Housing Complex',
      'group': 'Housing',
      'table': 'A',
      'order': 4,
    },

    // Lodging
    {
      'id': 'bed_and_breakfast',
      'label': 'Bed & Breakfast',
      'group': 'Lodging',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'budget_japanese_inn',
      'label': 'Budget Japanese Inn',
      'group': 'Lodging',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'campground',
      'label': 'Campground',
      'group': 'Lodging',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'camping_cabin',
      'label': 'Camping Cabin',
      'group': 'Lodging',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'cottage',
      'label': 'Cottage',
      'group': 'Lodging',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'extended_stay_hotel',
      'label': 'Extended Stay Hotel',
      'group': 'Lodging',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'farmstay',
      'label': 'Farmstay',
      'group': 'Lodging',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'guest_house',
      'label': 'Guest House',
      'group': 'Lodging',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'hostel',
      'label': 'Hostel',
      'group': 'Lodging',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'hotel',
      'label': 'Hotel',
      'group': 'Lodging',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'inn',
      'label': 'Inn',
      'group': 'Lodging',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'japanese_inn',
      'label': 'Japanese Inn',
      'group': 'Lodging',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'lodging',
      'label': 'Lodging',
      'group': 'Lodging',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'mobile_home_park',
      'label': 'Mobile Home Park',
      'group': 'Lodging',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'motel',
      'label': 'Motel',
      'group': 'Lodging',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'private_guest_room',
      'label': 'Private Guest Room',
      'group': 'Lodging',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'resort_hotel',
      'label': 'Resort Hotel',
      'group': 'Lodging',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'rv_park',
      'label': 'RV Park',
      'group': 'Lodging',
      'table': 'A',
      'order': 18,
    },

    // Natural Features
    {
      'id': 'beach',
      'label': 'Beach',
      'group': 'Natural Features',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'island',
      'label': 'Island',
      'group': 'Natural Features',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'lake',
      'label': 'Lake',
      'group': 'Natural Features',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'mountain_peak',
      'label': 'Mountain Peak',
      'group': 'Natural Features',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'nature_preserve',
      'label': 'Nature Preserve',
      'group': 'Natural Features',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'river',
      'label': 'River',
      'group': 'Natural Features',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'scenic_spot',
      'label': 'Scenic Spot',
      'group': 'Natural Features',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'woods',
      'label': 'Woods',
      'group': 'Natural Features',
      'table': 'A',
      'order': 8,
    },

    // Places of Worship
    {
      'id': 'buddhist_temple',
      'label': 'Buddhist Temple',
      'group': 'Places of Worship',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'church',
      'label': 'Church',
      'group': 'Places of Worship',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'hindu_temple',
      'label': 'Hindu Temple',
      'group': 'Places of Worship',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'mosque',
      'label': 'Mosque',
      'group': 'Places of Worship',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'shinto_shrine',
      'label': 'Shinto Shrine',
      'group': 'Places of Worship',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'synagogue',
      'label': 'Synagogue',
      'group': 'Places of Worship',
      'table': 'A',
      'order': 6,
    },

    // Services
    {
      'id': 'aircraft_rental_service',
      'label': 'Aircraft Rental Service',
      'group': 'Services',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'association_or_organization',
      'label': 'Association or Organization',
      'group': 'Services',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'astrologer',
      'label': 'Astrologer',
      'group': 'Services',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'barber_shop',
      'label': 'Barber Shop',
      'group': 'Services',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'beautician',
      'label': 'Beautician',
      'group': 'Services',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'beauty_salon',
      'label': 'Beauty Salon',
      'group': 'Services',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'body_art_service',
      'label': 'Body Art Service',
      'group': 'Services',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'catering_service',
      'label': 'Catering Service',
      'group': 'Services',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'cemetery',
      'label': 'Cemetery',
      'group': 'Services',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'chauffeur_service',
      'label': 'Chauffeur Service',
      'group': 'Services',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'child_care_agency',
      'label': 'Child Care Agency',
      'group': 'Services',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'consultant',
      'label': 'Consultant',
      'group': 'Services',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'courier_service',
      'label': 'Courier Service',
      'group': 'Services',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'electrician',
      'label': 'Electrician',
      'group': 'Services',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'employment_agency',
      'label': 'Employment Agency',
      'group': 'Services',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'florist',
      'label': 'Florist',
      'group': 'Services',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'food_delivery',
      'label': 'Food Delivery',
      'group': 'Services',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'foot_care',
      'label': 'Foot Care',
      'group': 'Services',
      'table': 'A',
      'order': 18,
    },
    {
      'id': 'funeral_home',
      'label': 'Funeral Home',
      'group': 'Services',
      'table': 'A',
      'order': 19,
    },
    {
      'id': 'hair_care',
      'label': 'Hair Care',
      'group': 'Services',
      'table': 'A',
      'order': 20,
    },
    {
      'id': 'hair_salon',
      'label': 'Hair Salon',
      'group': 'Services',
      'table': 'A',
      'order': 21,
    },
    {
      'id': 'insurance_agency',
      'label': 'Insurance Agency',
      'group': 'Services',
      'table': 'A',
      'order': 22,
    },
    {
      'id': 'laundry',
      'label': 'Laundry',
      'group': 'Services',
      'table': 'A',
      'order': 23,
    },
    {
      'id': 'lawyer',
      'label': 'Lawyer',
      'group': 'Services',
      'table': 'A',
      'order': 24,
    },
    {
      'id': 'locksmith',
      'label': 'Locksmith',
      'group': 'Services',
      'table': 'A',
      'order': 25,
    },
    {
      'id': 'makeup_artist',
      'label': 'Makeup Artist',
      'group': 'Services',
      'table': 'A',
      'order': 26,
    },
    {
      'id': 'marketing_consultant',
      'label': 'Marketing Consultant',
      'group': 'Services',
      'table': 'A',
      'order': 27,
    },
    {
      'id': 'moving_company',
      'label': 'Moving Company',
      'group': 'Services',
      'table': 'A',
      'order': 28,
    },
    {
      'id': 'nail_salon',
      'label': 'Nail Salon',
      'group': 'Services',
      'table': 'A',
      'order': 29,
    },
    {
      'id': 'non_profit_organization',
      'label': 'Non-Profit Organization',
      'group': 'Services',
      'table': 'A',
      'order': 30,
    },
    {
      'id': 'painter',
      'label': 'Painter',
      'group': 'Services',
      'table': 'A',
      'order': 31,
    },
    {
      'id': 'pet_boarding_service',
      'label': 'Pet Boarding Service',
      'group': 'Services',
      'table': 'A',
      'order': 32,
    },
    {
      'id': 'pet_care',
      'label': 'Pet Care',
      'group': 'Services',
      'table': 'A',
      'order': 33,
    },
    {
      'id': 'plumber',
      'label': 'Plumber',
      'group': 'Services',
      'table': 'A',
      'order': 34,
    },
    {
      'id': 'psychic',
      'label': 'Psychic',
      'group': 'Services',
      'table': 'A',
      'order': 35,
    },
    {
      'id': 'real_estate_agency',
      'label': 'Real Estate Agency',
      'group': 'Services',
      'table': 'A',
      'order': 36,
    },
    {
      'id': 'roofing_contractor',
      'label': 'Roofing Contractor',
      'group': 'Services',
      'table': 'A',
      'order': 37,
    },
    {
      'id': 'service',
      'label': 'Service',
      'group': 'Services',
      'table': 'A',
      'order': 38,
    },
    {
      'id': 'shipping_service',
      'label': 'Shipping Service',
      'group': 'Services',
      'table': 'A',
      'order': 39,
    },
    {
      'id': 'storage',
      'label': 'Storage',
      'group': 'Services',
      'table': 'A',
      'order': 40,
    },
    {
      'id': 'summer_camp_organizer',
      'label': 'Summer Camp Organizer',
      'group': 'Services',
      'table': 'A',
      'order': 41,
    },
    {
      'id': 'tailor',
      'label': 'Tailor',
      'group': 'Services',
      'table': 'A',
      'order': 42,
    },
    {
      'id': 'telecommunications_service_provider',
      'label': 'Telecommunications Provider',
      'group': 'Services',
      'table': 'A',
      'order': 43,
    },
    {
      'id': 'tour_agency',
      'label': 'Tour Agency',
      'group': 'Services',
      'table': 'A',
      'order': 44,
    },
    {
      'id': 'tourist_information_center',
      'label': 'Tourist Information Center',
      'group': 'Services',
      'table': 'A',
      'order': 45,
    },
    {
      'id': 'travel_agency',
      'label': 'Travel Agency',
      'group': 'Services',
      'table': 'A',
      'order': 46,
    },
    {
      'id': 'veterinary_care',
      'label': 'Veterinary Care',
      'group': 'Services',
      'table': 'A',
      'order': 47,
    },

    // Shopping
    {
      'id': 'asian_grocery_store',
      'label': 'Asian Grocery Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'auto_parts_store',
      'label': 'Auto Parts Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'bicycle_store',
      'label': 'Bicycle Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'book_store',
      'label': 'Book Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'building_materials_store',
      'label': 'Building Materials Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'butcher_shop',
      'label': 'Butcher Shop',
      'group': 'Shopping',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'cell_phone_store',
      'label': 'Cell Phone Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'clothing_store',
      'label': 'Clothing Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'convenience_store',
      'label': 'Convenience Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'cosmetics_store',
      'label': 'Cosmetics Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'department_store',
      'label': 'Department Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'discount_store',
      'label': 'Discount Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'discount_supermarket',
      'label': 'Discount Supermarket',
      'group': 'Shopping',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'electronics_store',
      'label': 'Electronics Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'farmers_market',
      'label': 'Farmers Market',
      'group': 'Shopping',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'flea_market',
      'label': 'Flea Market',
      'group': 'Shopping',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'food_store',
      'label': 'Food Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'furniture_store',
      'label': 'Furniture Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 18,
    },
    {
      'id': 'garden_center',
      'label': 'Garden Center',
      'group': 'Shopping',
      'table': 'A',
      'order': 19,
    },
    {
      'id': 'general_store',
      'label': 'General Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 20,
    },
    {
      'id': 'gift_shop',
      'label': 'Gift Shop',
      'group': 'Shopping',
      'table': 'A',
      'order': 21,
    },
    {
      'id': 'grocery_store',
      'label': 'Grocery Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 22,
    },
    {
      'id': 'hardware_store',
      'label': 'Hardware Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 23,
    },
    {
      'id': 'health_food_store',
      'label': 'Health Food Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 24,
    },
    {
      'id': 'home_goods_store',
      'label': 'Home Goods Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 25,
    },
    {
      'id': 'home_improvement_store',
      'label': 'Home Improvement Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 26,
    },
    {
      'id': 'hypermarket',
      'label': 'Hypermarket',
      'group': 'Shopping',
      'table': 'A',
      'order': 27,
    },
    {
      'id': 'jewelry_store',
      'label': 'Jewelry Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 28,
    },
    {
      'id': 'liquor_store',
      'label': 'Liquor Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 29,
    },
    {
      'id': 'market',
      'label': 'Market',
      'group': 'Shopping',
      'table': 'A',
      'order': 30,
    },
    {
      'id': 'pet_store',
      'label': 'Pet Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 31,
    },
    {
      'id': 'shoe_store',
      'label': 'Shoe Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 32,
    },
    {
      'id': 'shopping_mall',
      'label': 'Shopping Mall',
      'group': 'Shopping',
      'table': 'A',
      'order': 33,
    },
    {
      'id': 'sporting_goods_store',
      'label': 'Sporting Goods Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 34,
    },
    {
      'id': 'sportswear_store',
      'label': 'Sportswear Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 35,
    },
    {
      'id': 'store',
      'label': 'Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 36,
    },
    {
      'id': 'supermarket',
      'label': 'Supermarket',
      'group': 'Shopping',
      'table': 'A',
      'order': 37,
    },
    {
      'id': 'tea_store',
      'label': 'Tea Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 38,
    },
    {
      'id': 'thrift_store',
      'label': 'Thrift Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 39,
    },
    {
      'id': 'toy_store',
      'label': 'Toy Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 40,
    },
    {
      'id': 'warehouse_store',
      'label': 'Warehouse Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 41,
    },
    {
      'id': 'wholesaler',
      'label': 'Wholesaler',
      'group': 'Shopping',
      'table': 'A',
      'order': 42,
    },
    {
      'id': 'womens_clothing_store',
      'label': 'Womens Clothing Store',
      'group': 'Shopping',
      'table': 'A',
      'order': 43,
    },

    // Sports
    {
      'id': 'arena',
      'label': 'Arena',
      'group': 'Sports',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'athletic_field',
      'label': 'Athletic Field',
      'group': 'Sports',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'fishing_charter',
      'label': 'Fishing Charter',
      'group': 'Sports',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'fishing_pier',
      'label': 'Fishing Pier',
      'group': 'Sports',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'fishing_pond',
      'label': 'Fishing Pond',
      'group': 'Sports',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'fitness_center',
      'label': 'Fitness Center',
      'group': 'Sports',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'golf_course',
      'label': 'Golf Course',
      'group': 'Sports',
      'table': 'A',
      'order': 7,
    },
    {'id': 'gym', 'label': 'Gym', 'group': 'Sports', 'table': 'A', 'order': 8},
    {
      'id': 'ice_skating_rink',
      'label': 'Ice Skating Rink',
      'group': 'Sports',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'indoor_golf_course',
      'label': 'Indoor Golf Course',
      'group': 'Sports',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'playground',
      'label': 'Playground',
      'group': 'Sports',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'race_course',
      'label': 'Race Course',
      'group': 'Sports',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'ski_resort',
      'label': 'Ski Resort',
      'group': 'Sports',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'sports_activity_location',
      'label': 'Sports Activity Location',
      'group': 'Sports',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'sports_club',
      'label': 'Sports Club',
      'group': 'Sports',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'sports_coaching',
      'label': 'Sports Coaching',
      'group': 'Sports',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'sports_complex',
      'label': 'Sports Complex',
      'group': 'Sports',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'sports_school',
      'label': 'Sports School',
      'group': 'Sports',
      'table': 'A',
      'order': 18,
    },
    {
      'id': 'stadium',
      'label': 'Stadium',
      'group': 'Sports',
      'table': 'A',
      'order': 19,
    },
    {
      'id': 'swimming_pool',
      'label': 'Swimming Pool',
      'group': 'Sports',
      'table': 'A',
      'order': 20,
    },
    {
      'id': 'tennis_court',
      'label': 'Tennis Court',
      'group': 'Sports',
      'table': 'A',
      'order': 21,
    },

    // Transportation
    {
      'id': 'airport',
      'label': 'Airport',
      'group': 'Transportation',
      'table': 'A',
      'order': 1,
    },
    {
      'id': 'airstrip',
      'label': 'Airstrip',
      'group': 'Transportation',
      'table': 'A',
      'order': 2,
    },
    {
      'id': 'bike_sharing_station',
      'label': 'Bike Sharing Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 3,
    },
    {
      'id': 'bridge',
      'label': 'Bridge',
      'group': 'Transportation',
      'table': 'A',
      'order': 4,
    },
    {
      'id': 'bus_station',
      'label': 'Bus Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 5,
    },
    {
      'id': 'bus_stop',
      'label': 'Bus Stop',
      'group': 'Transportation',
      'table': 'A',
      'order': 6,
    },
    {
      'id': 'ferry_service',
      'label': 'Ferry Service',
      'group': 'Transportation',
      'table': 'A',
      'order': 7,
    },
    {
      'id': 'ferry_terminal',
      'label': 'Ferry Terminal',
      'group': 'Transportation',
      'table': 'A',
      'order': 8,
    },
    {
      'id': 'heliport',
      'label': 'Heliport',
      'group': 'Transportation',
      'table': 'A',
      'order': 9,
    },
    {
      'id': 'international_airport',
      'label': 'International Airport',
      'group': 'Transportation',
      'table': 'A',
      'order': 10,
    },
    {
      'id': 'light_rail_station',
      'label': 'Light Rail Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 11,
    },
    {
      'id': 'park_and_ride',
      'label': 'Park & Ride',
      'group': 'Transportation',
      'table': 'A',
      'order': 12,
    },
    {
      'id': 'subway_station',
      'label': 'Subway Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 13,
    },
    {
      'id': 'taxi_service',
      'label': 'Taxi Service',
      'group': 'Transportation',
      'table': 'A',
      'order': 14,
    },
    {
      'id': 'taxi_stand',
      'label': 'Taxi Stand',
      'group': 'Transportation',
      'table': 'A',
      'order': 15,
    },
    {
      'id': 'toll_station',
      'label': 'Toll Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 16,
    },
    {
      'id': 'train_station',
      'label': 'Train Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 17,
    },
    {
      'id': 'train_ticket_office',
      'label': 'Train Ticket Office',
      'group': 'Transportation',
      'table': 'A',
      'order': 18,
    },
    {
      'id': 'tram_stop',
      'label': 'Tram Stop',
      'group': 'Transportation',
      'table': 'A',
      'order': 19,
    },
    {
      'id': 'transit_depot',
      'label': 'Transit Depot',
      'group': 'Transportation',
      'table': 'A',
      'order': 20,
    },
    {
      'id': 'transit_station',
      'label': 'Transit Station',
      'group': 'Transportation',
      'table': 'A',
      'order': 21,
    },
    {
      'id': 'transit_stop',
      'label': 'Transit Stop',
      'group': 'Transportation',
      'table': 'A',
      'order': 22,
    },
    {
      'id': 'transportation_service',
      'label': 'Transportation Service',
      'group': 'Transportation',
      'table': 'A',
      'order': 23,
    },
    {
      'id': 'truck_stop',
      'label': 'Truck Stop',
      'group': 'Transportation',
      'table': 'A',
      'order': 24,
    },

    // Table B - Additional Place Types
    {
      'id': 'administrative_area_level_3',
      'label': 'Administrative Area Level 3',
      'group': 'Additional Types',
      'table': 'B',
      'order': 1,
    },
    {
      'id': 'administrative_area_level_4',
      'label': 'Administrative Area Level 4',
      'group': 'Additional Types',
      'table': 'B',
      'order': 2,
    },
    {
      'id': 'administrative_area_level_5',
      'label': 'Administrative Area Level 5',
      'group': 'Additional Types',
      'table': 'B',
      'order': 3,
    },
    {
      'id': 'administrative_area_level_6',
      'label': 'Administrative Area Level 6',
      'group': 'Additional Types',
      'table': 'B',
      'order': 4,
    },
    {
      'id': 'administrative_area_level_7',
      'label': 'Administrative Area Level 7',
      'group': 'Additional Types',
      'table': 'B',
      'order': 5,
    },
    {
      'id': 'archipelago',
      'label': 'Archipelago',
      'group': 'Additional Types',
      'table': 'B',
      'order': 6,
    },
    {
      'id': 'colloquial_area',
      'label': 'Colloquial Area',
      'group': 'Additional Types',
      'table': 'B',
      'order': 7,
    },
    {
      'id': 'continent',
      'label': 'Continent',
      'group': 'Additional Types',
      'table': 'B',
      'order': 8,
    },
    {
      'id': 'establishment',
      'label': 'Establishment',
      'group': 'Additional Types',
      'table': 'B',
      'order': 9,
    },
    {
      'id': 'finance',
      'label': 'Finance',
      'group': 'Additional Types',
      'table': 'B',
      'order': 10,
    },
    {
      'id': 'food',
      'label': 'Food',
      'group': 'Additional Types',
      'table': 'B',
      'order': 11,
    },
    {
      'id': 'general_contractor',
      'label': 'General Contractor',
      'group': 'Additional Types',
      'table': 'B',
      'order': 12,
    },
    {
      'id': 'geocode',
      'label': 'Geocode',
      'group': 'Additional Types',
      'table': 'B',
      'order': 13,
    },
    {
      'id': 'health',
      'label': 'Health',
      'group': 'Additional Types',
      'table': 'B',
      'order': 14,
    },
    {
      'id': 'intersection',
      'label': 'Intersection',
      'group': 'Additional Types',
      'table': 'B',
      'order': 15,
    },
    {
      'id': 'landmark',
      'label': 'Landmark',
      'group': 'Additional Types',
      'table': 'B',
      'order': 16,
    },
    {
      'id': 'natural_feature',
      'label': 'Natural Feature',
      'group': 'Additional Types',
      'table': 'B',
      'order': 17,
    },
    {
      'id': 'neighborhood',
      'label': 'Neighborhood',
      'group': 'Additional Types',
      'table': 'B',
      'order': 18,
    },
    {
      'id': 'place_of_worship',
      'label': 'Place of Worship',
      'group': 'Additional Types',
      'table': 'B',
      'order': 19,
    },
    {
      'id': 'plus_code',
      'label': 'Plus Code',
      'group': 'Additional Types',
      'table': 'B',
      'order': 20,
    },
    {
      'id': 'point_of_interest',
      'label': 'Point of Interest',
      'group': 'Additional Types',
      'table': 'B',
      'order': 21,
    },
    {
      'id': 'political',
      'label': 'Political',
      'group': 'Additional Types',
      'table': 'B',
      'order': 22,
    },
    {
      'id': 'postal_code_prefix',
      'label': 'Postal Code Prefix',
      'group': 'Additional Types',
      'table': 'B',
      'order': 23,
    },
    {
      'id': 'postal_code_suffix',
      'label': 'Postal Code Suffix',
      'group': 'Additional Types',
      'table': 'B',
      'order': 24,
    },
    {
      'id': 'postal_town',
      'label': 'Postal Town',
      'group': 'Additional Types',
      'table': 'B',
      'order': 25,
    },
    {
      'id': 'premise',
      'label': 'Premise',
      'group': 'Additional Types',
      'table': 'B',
      'order': 26,
    },
    {
      'id': 'route',
      'label': 'Route',
      'group': 'Additional Types',
      'table': 'B',
      'order': 27,
    },
    {
      'id': 'street_address',
      'label': 'Street Address',
      'group': 'Additional Types',
      'table': 'B',
      'order': 28,
    },
    {
      'id': 'sublocality',
      'label': 'Sublocality',
      'group': 'Additional Types',
      'table': 'B',
      'order': 29,
    },
    {
      'id': 'sublocality_level_1',
      'label': 'Sublocality Level 1',
      'group': 'Additional Types',
      'table': 'B',
      'order': 30,
    },
    {
      'id': 'sublocality_level_2',
      'label': 'Sublocality Level 2',
      'group': 'Additional Types',
      'table': 'B',
      'order': 31,
    },
    {
      'id': 'sublocality_level_3',
      'label': 'Sublocality Level 3',
      'group': 'Additional Types',
      'table': 'B',
      'order': 32,
    },
    {
      'id': 'sublocality_level_4',
      'label': 'Sublocality Level 4',
      'group': 'Additional Types',
      'table': 'B',
      'order': 33,
    },
    {
      'id': 'sublocality_level_5',
      'label': 'Sublocality Level 5',
      'group': 'Additional Types',
      'table': 'B',
      'order': 34,
    },
    {
      'id': 'subpremise',
      'label': 'Subpremise',
      'group': 'Additional Types',
      'table': 'B',
      'order': 35,
    },
    {
      'id': 'town_square',
      'label': 'Town Square',
      'group': 'Additional Types',
      'table': 'B',
      'order': 36,
    },
  ];
}
