// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAbZ12-B79x1AjQVTR4tUd0-ZVyPvUBM',
    appId: '1:671200983653:web:d8f593d767362fc853648c',
    messagingSenderId: '671200983653',
    projectId: 'atlas-558eb',
    authDomain: 'atlas-558eb.firebaseapp.com',
    storageBucket: 'atlas-558eb.firebasestorage.app',
    measurementId: 'G-DJVQC1P8CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaJSe-vyabtoq9vDAKeAlbg49fx3FtYgI',
    appId: '1:671200983653:android:1f9cf8242f8250be53648c',
    messagingSenderId: '671200983653',
    projectId: 'atlas-558eb',
    storageBucket: 'atlas-558eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzj-l6u9YTb6GhR4OcxHDp_1bo8UqTWJM',
    appId: '1:671200983653:ios:c7f8ea874bbdab4d53648c',
    messagingSenderId: '671200983653',
    projectId: 'atlas-558eb',
    storageBucket: 'atlas-558eb.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzj-l6u9YTb6GhR4OcxHDp_1bo8UqTWJM',
    appId: '1:671200983653:ios:c7f8ea874bbdab4d53648c',
    messagingSenderId: '671200983653',
    projectId: 'atlas-558eb',
    storageBucket: 'atlas-558eb.firebasestorage.app',
    iosBundleId: 'com.example.atlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoAbZ12-B79x1AjQVTR4tUd0-ZVyPvUBM',
    appId: '1:671200983653:web:49f9f4f3e3a5052a53648c',
    messagingSenderId: '671200983653',
    projectId: 'atlas-558eb',
    authDomain: 'atlas-558eb.firebaseapp.com',
    storageBucket: 'atlas-558eb.firebasestorage.app',
    measurementId: 'G-3B1V0HG1Q1',
  );
}
