import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ru')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key) {
    return _strings[locale.languageCode]?[key] ?? _strings['en']![key] ?? key;
  }

  String n(
    String oneKey,
    String manyKey,
    int count, {
    bool includeCount = true,
  }) {
    final key = count == 1 ? oneKey : manyKey;
    final value = t(key);
    return includeCount ? '$count $value' : value;
  }

  String count(String key, int count) => t(key).replaceAll('{count}', '$count');

  String named(String key, Map<String, Object?> values) {
    var value = t(key);
    values.forEach((name, replacement) {
      value = value.replaceAll('{$name}', replacement?.toString() ?? '');
    });
    return value;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ru'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(
      locale.languageCode == 'ru' ? const Locale('ru') : const Locale('en'),
    );
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

const _strings = {
  'en': {
    'account': 'Account',
    'accountCreated': 'Account has been successfully created!',
    'addPhoto': 'Add photo',
    'addReview': 'Add review',
    'addToPlannedTrips': 'Add to Planned Trips',
    'addedHotels': 'Added hotels',
    'addedPlaces': 'Added places',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'allPlaces': 'All Places',
    'amazing': 'Amazing!',
    'appVersion': 'App version',
    'appearance': 'Appearance',
    'achievements': 'Achievements',
    'achievementsUnlocked': '{unlocked}/{total} unlocked',
    'applyFilters': 'Apply Filters',
    'applyFiltersCount': 'Apply {count} filters',
    'applyProfileChanges': 'Apply profile changes',
    'artGalleries': 'Art Galleries',
    'atlasNeedsOrigin': 'Atlas needs a start point to build Google routes.',
    'authSubtitleSignIn': 'Your next destination is one step away.',
    'authSubtitleSignUp': 'Thousands of places. One account.',
    'avatarPickerNotReady':
        'Avatar picker is not ready yet. Please fully stop the app and run it again.',
    'back': 'Back',
    'bars': 'Bars',
    'biometricLogin': 'Biometric login',
    'biometricLoginDisabled': 'Biometric login disabled.',
    'biometricLoginEnabled': 'Biometric login enabled.',
    'biometricLoginReason': 'Confirm your identity to enable biometric login.',
    'biometricLoginSubtitle': 'Use Face ID or Touch ID when signing in',
    'biometricLoginUnavailable':
        'Biometric authentication is not available on this device.',
    'buildingRoutes': 'Building routes...',
    'cafes': 'Cafes',
    'cancel': 'Cancel',
    'categoriesSelected': '{count} categories selected',
    'chooseDestination': 'Choose destination',
    'chooseFromGallery': 'Choose from gallery',
    'chooseOrigin': 'Choose origin',
    'choosePreferencesToContinue': 'Choose your preferences to continue',
    'chooseRouteBeforeSaving': 'Choose a route before saving.',
    'chooseStartPoint': 'Choose start point',
    'chosenHotels': 'Chosen hotels',
    'chosenPlaces': 'Chosen places',
    'confirmPassword': 'Confirm Password',
    'clearAll': 'Clear All',
    'clearFilter': 'Clear filter',
    'closer': 'Closer',
    'clearLocalCache': 'Clear local cache/history',
    'clearLocalCacheSubtitle': 'Remove recent searches on this device',
    'contactSupport': 'Contact support / feedback',
    'contactSupportMessage':
        'Email support@atlas.app with your feedback, bug reports, or feature ideas.',
    'contactSupportSubtitle': 'Send feedback to the Atlas team',
    'couldNotBuildRoutes': 'Couldn’t build routes',
    'couldNotLoadList': 'Couldn’t load this list',
    'couldNotLoadSearchResults': 'Couldn’t load search results',
    'createAccount': 'Create Account',
    'couldBeBetter': 'Could be better',
    'currency': 'Currency',
    'currentPosition': 'Current position',
    'delete': 'Delete',
    'deleteAccount': 'Delete account',
    'deleteAccountMessage':
        'This removes your profile, favorites, reviews, and trips.',
    'deleteAccountSubtitle': 'Permanently remove your Atlas account',
    'deleteAccountTitle': 'Delete account?',
    'deleteReviewMessage': 'Remove your review for "{place}"?',
    'deleteReviewTitle': 'Delete review?',
    'deleteTripMessage': 'Remove "{title}" from your planned trips?',
    'deleteTripTitle': 'Delete trip?',
    'dark': 'Dark',
    'details': 'Details',
    'direct': 'Direct',
    'directFlight': 'Direct flight',
    'distanceUnit': 'Distance Unit',
    'dontHaveAccount': 'Don’t have an account? Sign up',
    'editProfile': 'Edit profile',
    'editReview': 'Edit review',
    'email': 'Email',
    'estimated': 'Estimated',
    'exploreDestination': 'Explore this destination',
    'favouritePlaces': 'Favourite Places',
    'failedLoadProfile': 'Failed to load your profile.',
    'failedOpenPhotoLibrary': 'Failed to open photo library. Please try again.',
    'farther': 'Farther',
    'findingCurrentLocation': 'Finding your current location...',
    'foundResults': 'Found {count} {label}',
    'fixedRoute': 'Fixed route',
    'foundOneWay': 'Found {count} way',
    'foundWays': 'Found {count} ways',
    'good': 'Good',
    'great': 'Great!',
    'home': 'Home',
    'hotels': 'Hotels',
    'hotelsNearby': 'Hotels nearby',
    'hotPlacesUnavailable': 'Hot places unavailable',
    'howWasVisit': 'How was your visit?',
    'itinerary': 'Itinerary',
    'kilometers': 'Kilometers',
    'language': 'Language',
    'light': 'Light',
    'loadingPlaceInfo': 'Loading place info...',
    'localHistoryCleared': 'Local search history cleared.',
    'locationUnavailable': 'Location unavailable',
    'logOut': 'Log out',
    'makeItYours': 'Make It Yours.',
    'mapLocation': 'Map location',
    'maxPhotosAdded': 'Maximum photos added',
    'museums': 'Museums',
    'mustSee': 'Must See',
    'miles': 'Miles',
    'newHorizons': 'New\nHorizons.',
    'newPlace': 'New place',
    'nearbyPlace': 'Nearby place',
    'newExplorer': 'New Explorer',
    'noCommunityFavourites': 'No community favourites yet.',
    'noFavouritePlaces': 'No favourite places yet',
    'noFavouritePlacesMessage':
        'Save places you love from the place page, then revisit them here.',
    'noMatchesFound': 'No matches found',
    'noPlaceInfoHere': 'No place information found here.',
    'noPreferencesSaved': 'Save without preferences',
    'noRecommendations': 'No recommendations yet.',
    'noReviewsAvailable': 'No reviews are available for this place yet.',
    'noReviewsYet': 'No reviews yet',
    'noReviewsYetMessage':
        'Create and edit your own saved reviews here whenever you want.',
    'noReviewsPreview':
        'No reviews yet. This place will show Google reviews first and Atlas user reviews as they are added.',
    'noRoutesAvailable':
        'No routes are available for these locations right now.',
    'noRoutesFound': 'No routes found',
    'noTripsPlanned': 'No trips planned yet',
    'noTripsPlannedMessage':
        'Save a route from the planner so it is ready when you need it.',
    'notGreat': 'Not great',
    'notInterestingAnymore': 'Not interesting anymore',
    'ok': 'OK',
    'openReviewsForPlace': 'Open reviews for this place',
    'parks': 'Parks',
    'password': 'Password',
    'passwordTooShort': 'Password must be at least 6 characters',
    'passwordsDoNotMatch': 'Passwords do not match',
    'personalization': 'Personalization',
    'pickedForYou': 'Picked for you',
    'placeName': 'Place name',
    'placeNameRequired': 'Place name is required.',
    'placeType': 'Place Type',
    'placeTypesCount': '{count} place types',
    'placeUnavailable': 'Place unavailable',
    'placeDescriptionNoLocation':
        '{place} is waiting to be explored. Detailed editorial description is not available for this place yet.',
    'placeDescriptionWithLocation':
        '{place} is located in {location}. Detailed editorial description is not available for this place yet, but you can still explore photos and reviews before planning your visit.',
    'plannedTrips': 'Planned Trips',
    'planJourney': 'Plan journey',
    'preferences': 'Preferences',
    'preferencesUnavailable': 'Preferences unavailable',
    'preferencesIntro': 'Choose precisely to personalise your experience, ',
    'preferencesUpdated': 'Preferences updated.',
    'privacyData': 'Privacy & Data',
    'profile': 'Profile',
    'profileUnavailable': 'Profile unavailable',
    'profileUpdated': 'Profile updated.',
    'publicReviews': 'Public reviews',
    'popular': 'Popular',
    'pullToRefresh': 'Pull down from the top to refresh.',
    'pullToTryAgain': 'Pull down from the top to try again.',
    'readMore': 'Read More',
    'recentRequests': 'Recent Requests',
    'recentRequest': 'Recent request',
    'recommendationNotifications': 'Recommendation notifications',
    'recommendationNotificationsSubtitle':
        'Get prompts when Atlas finds new ideas',
    'recommended': 'Recommended',
    'recommendationsUnavailable': 'Recommendations unavailable',
    'region': 'Region',
    'removeAvatar': 'Remove avatar',
    'remove': 'Remove',
    'removePhoto': 'Remove photo',
    'restaurant': 'Restaurants',
    'result': 'Result',
    'results': 'Results',
    'returnToSignIn': 'Return to sign in',
    'reviewAdded': 'Review added.',
    'reviewDeleted': 'Review deleted.',
    'reviewTextRequired': 'Review text is required.',
    'reviewHint': 'Add details about your experience...',
    'reviewUpdated': 'Review updated.',
    'reviews': 'Reviews',
    'reviewsCount': '{count} reviews',
    'reviewsArePrivate': 'Reviews are private.',
    'reviewsArePublic': 'Reviews are public.',
    'reviewsPrivateSubtitle': 'Reviews stay private to your profile',
    'reviewsPublicSubtitle': 'Your name and avatar can appear on reviews',
    'routeDetails': 'Route details',
    'routeBest': 'Recommended route',
    'routeBus': 'Bus route',
    'routeCar': 'Driving route',
    'routeFlight': 'Flight route',
    'routeTrain': 'Train route',
    'directRoute': 'Direct',
    'transferRoute': '{count} transfer',
    'transfersRoute': '{count} transfers',
    'publicTransport': 'Public transport',
    'drive': 'Drive',
    'walk': 'Walk',
    'bike': 'Bike',
    'flight': 'Flight',
    'bus': 'Bus',
    'train': 'Train',
    'subway': 'Subway',
    'tram': 'Tram',
    'transfer': 'Transfer',
    'driveTo': 'Drive to {place}',
    'busTo': 'Bus to {place}',
    'trainTo': 'Train to {place}',
    'flyTo': 'Fly to {place}',
    'fromTo': '{from} to {to}',
    'fromPrice': 'from {price}',
    'dayShort': 'd',
    'dayWord': 'day',
    'daysWord': 'days',
    'hourWord': 'hour',
    'hoursWord': 'hours',
    'hoursFewWord': 'hours',
    'hoursManyWord': 'hours',
    'minuteShort': 'm',
    'minutesWord': 'min',
    'badgeBeachLoverDescription': 'Visited 5 beaches',
    'badgeBeachLoverTitle': 'Beach Lover',
    'badgeBorderStarterDescription': 'Explored 2 different countries',
    'badgeBorderStarterTitle': 'Border Starter',
    'badgeCityCollectorDescription': 'Visited 10 places in one city',
    'badgeCityCollectorTitle': 'City Collector',
    'badgeCitySamplerDescription': 'Explored 3 different cities',
    'badgeCitySamplerTitle': 'City Sampler',
    'badgeCountryHopperDescription': 'Visited places in 5 countries',
    'badgeCountryHopperTitle': 'Country Hopper',
    'badgeEarlyExplorerDescription': 'Added recent travel activity',
    'badgeEarlyExplorerTitle': 'Early Explorer',
    'badgeFoodHunterDescription': 'Reviewed 10 restaurants',
    'badgeFoodHunterTitle': 'Food Hunter',
    'badgeGreatTasteDescription': 'Found 5 places rated 4 stars or higher',
    'badgeGreatTasteTitle': 'Great Taste',
    'badgeHiddenGemFinderDescription': 'Reviewed low-key local places',
    'badgeHiddenGemFinderTitle': 'Hidden Gem Finder',
    'badgeLocalGuideDescription': 'Wrote 20 helpful reviews',
    'badgeLocalGuideTitle': 'Local Guide',
    'badgeMuseumMindDescription': 'Visited 5 museums',
    'badgeMuseumMindTitle': 'Museum Mind',
    'badgeOpinionMakerDescription': 'Wrote 5 reviews',
    'badgeOpinionMakerTitle': 'Opinion Maker',
    'badgePhotoReviewerDescription': 'Added photos to 5 reviews',
    'badgePhotoReviewerTitle': 'Photo Reviewer',
    'badgePhotoTravelerDescription': 'Uploaded 30 travel photos',
    'badgePhotoTravelerTitle': 'Photo Traveler',
    'badgePlaceCollectorDescription': 'Saved, reviewed, or planned 25 places',
    'badgePlaceCollectorTitle': 'Place Collector',
    'badgeRouteMakerDescription': 'Saved 3 planned trips',
    'badgeRouteMakerTitle': 'Route Maker',
    'badgeStorytellerDescription': 'Wrote 5 detailed reviews',
    'badgeStorytellerTitle': 'Storyteller',
    'badgeStyleSamplerDescription': 'Explored 5 travel categories',
    'badgeStyleSamplerTitle': 'Style Sampler',
    'badgeTagCuratorDescription': 'Added tags to 10 reviews',
    'badgeTagCuratorTitle': 'Tag Curator',
    'badgeWeekendExplorerDescription': 'Visited 3 places in one weekend',
    'badgeWeekendExplorerTitle': 'Weekend Explorer',
    'levelCityScout': 'City Scout',
    'levelLocalExpert': 'Local Expert',
    'levelNewExplorer': 'New Explorer',
    'levelRouteBuilder': 'Route Builder',
    'levelTravelLegend': 'Travel Legend',
    'levelWeekendTraveler': 'Weekend Traveler',
    'levelWorldExplorer': 'World Explorer',
    'savedNotes': 'Saved notes',
    'savedRoute': 'Saved Route',
    'savedRouteFallback': 'Saved route',
    'savedPlacesCount': '{count} saved places',
    'savePreferencesCount': 'Save {count} preferences',
    'search': 'Search',
    'searchFilters': 'Search Filters',
    'searchHint': 'Search places, cities, landmarks...',
    'searchLocationHint': 'Search city, airport, station, address...',
    'searching': 'Searching...',
    'settings': 'Settings',
    'settingsSubtitle': 'Tune Atlas around how you travel.',
    'setupLater': 'or set it up later.',
    'shareVisitDetails': 'Share details from your visit',
    'shopping': 'Shopping',
    'showLess': 'Show Less',
    'signIn': 'Sign In',
    'slideToContinue': 'Slide to continue',
    'splashHeadline': 'Some places\nchange you\nforever.',
    'splashSubtitle': 'Discover, plan and explore with Atlas.',
    'startJourney': 'Start a Journey!',
    'starRating': '{count} stars',
    'submitReview': 'Submit review',
    'support': 'Support',
    'system': 'System',
    'switchToMapMode': 'Switch to {label}',
    'tapToEditReview': 'Tap to edit this review',
    'termsPrivacy': 'Terms / Privacy policy',
    'termsPrivacyMessage':
        'Atlas stores profile, preference, favorite, review, and trip data to provide recommendations and sync your travel activity. Add your final legal text or external policy links here before release.',
    'termsPrivacySubtitle': 'Read Atlas terms and privacy notes',
    'theme': 'Theme',
    'touristAttractions': 'Tourist Attractions',
    'trendingToday': 'Trending today in Atlas',
    'tripsPlannedCount': '{count} trips planned',
    'tripDeleted': 'Trip deleted.',
    'tripSavedToPlannedTrips': 'Trip saved to Planned Trips.',
    'tryAnotherRoute':
        'Try another start point, destination, or check API coverage later.',
    'tryMoreDetails':
        'Try a place name, city, or landmark with a little more detail.',
    'updateReview': 'Update review',
    'useFavorites': 'Use favorites',
    'useFavoritesSubtitle': 'Improve recommendations from saved places',
    'useReviews': 'Use reviews',
    'useReviewsSubtitle': 'Improve recommendations from your ratings',
    'username': 'Username',
    'unnamedPlace': 'Unnamed place',
    'usernameCannotBeEmpty': 'Username cannot be empty.',
    'welcomeBack': 'Welcome Back.',
    'welcomeUser': 'Welcome, {username}!',
    'youCanAlsoVisit': 'You can also visit',
    'youAreCurrentlyIn': 'You’re currently in',
    'yourFeedbackHelps': 'Your feedback helps other travelers',
    'yourSelectedArea': 'your selected area',
    'zoos': 'Zoos',
  },
  'ru': {
    'account': 'Аккаунт',
    'accountCreated': 'Аккаунт успешно создан!',
    'addPhoto': 'Добавить фото',
    'addReview': 'Добавить отзыв',
    'addToPlannedTrips': 'Добавить в планы',
    'addedHotels': 'Добавленные отели',
    'addedPlaces': 'Добавленные места',
    'alreadyHaveAccount': 'Уже есть аккаунт? Войти',
    'allPlaces': 'Все места',
    'amazing': 'Великолепно!',
    'appVersion': 'Версия приложения',
    'appearance': 'Оформление',
    'achievements': 'Достижения',
    'achievementsUnlocked': 'Открыто: {unlocked}/{total}',
    'applyFilters': 'Применить фильтры',
    'applyFiltersCount': 'Применить фильтров: {count}',
    'applyProfileChanges': 'Сохранить изменения профиля',
    'artGalleries': 'Галереи',
    'atlasNeedsOrigin':
        'Atlas нужен начальный пункт, чтобы построить маршрут Google.',
    'authSubtitleSignIn': 'Следующее место уже совсем близко.',
    'authSubtitleSignUp': 'Тысячи мест. Один аккаунт.',
    'avatarPickerNotReady':
        'Выбор аватара пока не готов. Полностью остановите приложение и запустите снова.',
    'back': 'Назад',
    'bars': 'Бары',
    'biometricLogin': 'Вход по биометрии',
    'biometricLoginDisabled': 'Вход по биометрии отключен.',
    'biometricLoginEnabled': 'Вход по биометрии включен.',
    'biometricLoginReason':
        'Подтвердите личность, чтобы включить вход по биометрии.',
    'biometricLoginSubtitle': 'Использовать Face ID или Touch ID при входе',
    'biometricLoginUnavailable':
        'Биометрическая аутентификация недоступна на этом устройстве.',
    'buildingRoutes': 'Строим маршруты...',
    'cafes': 'Кафе',
    'cancel': 'Отмена',
    'categoriesSelected': 'Выбрано категорий: {count}',
    'chooseDestination': 'Выбрать пункт назначения',
    'chooseFromGallery': 'Выбрать из галереи',
    'chooseOrigin': 'Выбрать начало',
    'choosePreferencesToContinue': 'Выберите предпочтения, чтобы продолжить',
    'chooseRouteBeforeSaving': 'Выберите маршрут перед сохранением.',
    'chooseStartPoint': 'Выбрать начальный пункт',
    'chosenHotels': 'Выбранные отели',
    'chosenPlaces': 'Выбранные места',
    'confirmPassword': 'Подтвердите пароль',
    'clearAll': 'Очистить все',
    'clearFilter': 'Сбросить фильтр',
    'closer': 'Ближе',
    'clearLocalCache': 'Очистить локальный кеш/историю',
    'clearLocalCacheSubtitle':
        'Удалить недавние поисковые запросы на устройстве',
    'contactSupport': 'Поддержка / обратная связь',
    'contactSupportMessage':
        'Напишите на support@atlas.app с отзывами, ошибками или идеями.',
    'contactSupportSubtitle': 'Отправить отзыв команде Atlas',
    'couldNotBuildRoutes': 'Не удалось построить маршруты',
    'couldNotLoadList': 'Не удалось загрузить список',
    'couldNotLoadSearchResults': 'Не удалось загрузить результаты',
    'createAccount': 'Создать аккаунт',
    'couldBeBetter': 'Могло быть лучше',
    'currency': 'Валюта',
    'currentPosition': 'Текущая позиция',
    'delete': 'Удалить',
    'deleteAccount': 'Удалить аккаунт',
    'deleteAccountMessage':
        'Будут удалены профиль, избранное, отзывы и поездки.',
    'deleteAccountSubtitle': 'Навсегда удалить аккаунт Atlas',
    'deleteAccountTitle': 'Удалить аккаунт?',
    'deleteReviewMessage': 'Удалить ваш отзыв о «{place}»?',
    'deleteReviewTitle': 'Удалить отзыв?',
    'deleteTripMessage': 'Удалить «{title}» из запланированных поездок?',
    'deleteTripTitle': 'Удалить поездку?',
    'dark': 'Темная',
    'details': 'Детали',
    'direct': 'Прямой',
    'directFlight': 'Прямой рейс',
    'distanceUnit': 'Единицы расстояния',
    'dontHaveAccount': 'Нет аккаунта? Зарегистрироваться',
    'editProfile': 'Редактировать профиль',
    'editReview': 'Редактировать отзыв',
    'email': 'Email',
    'estimated': 'Оценочно',
    'exploreDestination': 'Исследовать это место',
    'favouritePlaces': 'Избранные места',
    'failedLoadProfile': 'Не удалось загрузить профиль.',
    'failedOpenPhotoLibrary': 'Не удалось открыть галерею. Попробуйте еще раз.',
    'farther': 'Дальше',
    'findingCurrentLocation': 'Определяем вашу текущую локацию...',
    'foundResults': 'Найдено: {count} {label}',
    'fixedRoute': 'Фиксированный маршрут',
    'foundOneWay': 'Найден {count} маршрут',
    'foundFewWays': 'Найдено {count} маршрута',
    'foundWays': 'Найдено {count} маршрутов',
    'good': 'Хорошо',
    'great': 'Отлично!',
    'home': 'Главная',
    'hotels': 'Отели',
    'hotelsNearby': 'Отели рядом',
    'hotPlacesUnavailable': 'Популярные места недоступны',
    'howWasVisit': 'Как прошел визит?',
    'itinerary': 'Маршрут',
    'kilometers': 'Километры',
    'language': 'Язык',
    'light': 'Светлая',
    'loadingPlaceInfo': 'Загружаем информацию о месте...',
    'localHistoryCleared': 'Локальная история поиска очищена.',
    'locationUnavailable': 'Локация недоступна',
    'logOut': 'Выйти',
    'makeItYours': 'Настройте под себя.',
    'mapLocation': 'Место на карте',
    'maxPhotosAdded': 'Добавлен максимум фото',
    'museums': 'Музеи',
    'mustSee': 'Обязательно посетить',
    'miles': 'Мили',
    'newHorizons': 'Новые\nгоризонты.',
    'newPlace': 'Новое место',
    'nearbyPlace': 'Место рядом',
    'newExplorer': 'Новый исследователь',
    'noCommunityFavourites': 'Пока нет избранного от сообщества.',
    'noFavouritePlaces': 'Пока нет избранных мест',
    'noFavouritePlacesMessage':
        'Сохраняйте любимые места со страницы места и возвращайтесь к ним здесь.',
    'noMatchesFound': 'Совпадений не найдено',
    'noPlaceInfoHere': 'Информация о месте здесь не найдена.',
    'noPreferencesSaved': 'Сохранить без предпочтений',
    'noRecommendations': 'Пока нет рекомендаций.',
    'noReviewsAvailable': 'Для этого места пока нет отзывов.',
    'noReviewsYet': 'Пока нет отзывов',
    'noReviewsYetMessage':
        'Создавайте и редактируйте сохраненные отзывы здесь в любое время.',
    'noReviewsPreview':
        'Пока нет отзывов. Здесь будут отзывы Google и пользователей Atlas.',
    'noRoutesAvailable': 'Сейчас для этих локаций нет доступных маршрутов.',
    'noRoutesFound': 'Маршруты не найдены',
    'noTripsPlanned': 'Пока нет запланированных поездок',
    'noTripsPlannedMessage':
        'Сохраните маршрут из планировщика, чтобы он был под рукой.',
    'notGreat': 'Не очень',
    'notInterestingAnymore': 'Больше не интересно',
    'ok': 'OK',
    'openReviewsForPlace': 'Открыть отзывы об этом месте',
    'parks': 'Парки',
    'password': 'Пароль',
    'passwordTooShort': 'Пароль должен быть не короче 6 символов',
    'passwordsDoNotMatch': 'Пароли не совпадают',
    'personalization': 'Персонализация',
    'pickedForYou': 'Подобрано для вас',
    'placeName': 'Название места',
    'placeNameRequired': 'Укажите название места.',
    'placeType': 'Тип места',
    'placeTypesCount': 'Типов мест: {count}',
    'placeUnavailable': 'Место недоступно',
    'placeDescriptionNoLocation':
        '{place} ждет, чтобы его исследовали. Подробное описание пока недоступно.',
    'placeDescriptionWithLocation':
        '{place} находится в {location}. Подробное описание пока недоступно, но вы можете посмотреть фото и отзывы перед поездкой.',
    'plannedTrips': 'Запланированные поездки',
    'planJourney': 'Спланировать поездку',
    'preferences': 'Предпочтения',
    'preferencesUnavailable': 'Предпочтения недоступны',
    'preferencesIntro': 'Выберите то, что вам интересно, ',
    'preferencesUpdated': 'Предпочтения обновлены.',
    'privacyData': 'Приватность и данные',
    'profile': 'Профиль',
    'profileUnavailable': 'Профиль недоступен',
    'profileUpdated': 'Профиль обновлен.',
    'publicReviews': 'Публичные отзывы',
    'popular': 'Популярно',
    'pullToRefresh': 'Потяните сверху вниз, чтобы обновить.',
    'pullToTryAgain': 'Потяните сверху вниз, чтобы попробовать снова.',
    'readMore': 'Читать дальше',
    'recentRequests': 'Недавние',
    'recentRequest': 'Недавний запрос',
    'recommendationNotifications': 'Уведомления с рекомендациями',
    'recommendationNotificationsSubtitle':
        'Получать подсказки, когда Atlas находит новые идеи',
    'recommended': 'Рекомендуем',
    'recommendationsUnavailable': 'Рекомендации недоступны',
    'region': 'Регион',
    'removeAvatar': 'Удалить аватар',
    'remove': 'Удалить',
    'removePhoto': 'Удалить фото',
    'restaurant': 'Рестораны',
    'result': 'результат',
    'results': 'результатов',
    'returnToSignIn': 'Вернуться ко входу',
    'reviewAdded': 'Отзыв добавлен.',
    'reviewDeleted': 'Отзыв удален.',
    'reviewTextRequired': 'Текст отзыва обязателен.',
    'reviewHint': 'Добавьте детали вашего опыта...',
    'reviewUpdated': 'Отзыв обновлен.',
    'reviews': 'Отзывы',
    'reviewsCount': 'Отзывов: {count}',
    'reviewsArePrivate': 'Отзывы скрыты.',
    'reviewsArePublic': 'Отзывы публичны.',
    'reviewsPrivateSubtitle': 'Отзывы видны только в вашем профиле',
    'reviewsPublicSubtitle': 'Ваше имя и аватар могут отображаться в отзывах',
    'routeDetails': 'Детали маршрута',
    'routeBest': 'Рекомендуемый маршрут',
    'routeBus': 'Автобусный маршрут',
    'routeCar': 'Маршрут на машине',
    'routeFlight': 'Маршрут с перелетом',
    'routeTrain': 'Маршрут на поезде',
    'directRoute': 'Прямой',
    'transferRoute': '{count} пересадка',
    'transfersRoute': '{count} пересадки',
    'publicTransport': 'Общественный транспорт',
    'drive': 'На машине',
    'walk': 'Пешком',
    'bike': 'На велосипеде',
    'flight': 'Перелет',
    'bus': 'Автобус',
    'train': 'Поезд',
    'subway': 'Метро',
    'tram': 'Трамвай',
    'transfer': 'Пересадка',
    'driveTo': 'На машине до {place}',
    'busTo': 'Автобус до {place}',
    'trainTo': 'Поезд до {place}',
    'flyTo': 'Перелет до {place}',
    'fromTo': '{from} → {to}',
    'fromPrice': 'от {price}',
    'dayShort': 'д',
    'dayWord': 'день',
    'daysWord': 'дня',
    'hourWord': 'час',
    'hoursWord': 'часа',
    'hoursFewWord': 'часа',
    'hoursManyWord': 'часов',
    'minuteShort': 'мин',
    'minutesWord': 'мин',
    'badgeBeachLoverDescription': 'Посетите 5 пляжей',
    'badgeBeachLoverTitle': 'Любитель пляжей',
    'badgeBorderStarterDescription': 'Исследуйте 2 разные страны',
    'badgeBorderStarterTitle': 'Первый рубеж',
    'badgeCityCollectorDescription': 'Посетите 10 мест в одном городе',
    'badgeCityCollectorTitle': 'Коллекционер города',
    'badgeCitySamplerDescription': 'Исследуйте 3 разных города',
    'badgeCitySamplerTitle': 'Городской дегустатор',
    'badgeCountryHopperDescription': 'Посетите места в 5 странах',
    'badgeCountryHopperTitle': 'По странам',
    'badgeEarlyExplorerDescription': 'Добавьте недавнюю активность',
    'badgeEarlyExplorerTitle': 'Первые открытия',
    'badgeFoodHunterDescription': 'Оставьте отзывы о 10 ресторанах',
    'badgeFoodHunterTitle': 'Охотник за вкусом',
    'badgeGreatTasteDescription': 'Найдите 5 мест с оценкой 4+',
    'badgeGreatTasteTitle': 'Отличный вкус',
    'badgeHiddenGemFinderDescription': 'Оставьте отзывы о локальных местах',
    'badgeHiddenGemFinderTitle': 'Искатель жемчужин',
    'badgeLocalGuideDescription': 'Напишите 20 полезных отзывов',
    'badgeLocalGuideTitle': 'Локальный гид',
    'badgeMuseumMindDescription': 'Посетите 5 музеев',
    'badgeMuseumMindTitle': 'Музейный ум',
    'badgeOpinionMakerDescription': 'Напишите 5 отзывов',
    'badgeOpinionMakerTitle': 'Автор мнений',
    'badgePhotoReviewerDescription': 'Добавьте фото к 5 отзывам',
    'badgePhotoReviewerTitle': 'Фото-отзывы',
    'badgePhotoTravelerDescription': 'Загрузите 30 фото из поездок',
    'badgePhotoTravelerTitle': 'Фотопутешественник',
    'badgePlaceCollectorDescription':
        'Сохраните, оцените или запланируйте 25 мест',
    'badgePlaceCollectorTitle': 'Коллекционер мест',
    'badgeRouteMakerDescription': 'Сохраните 3 запланированные поездки',
    'badgeRouteMakerTitle': 'Создатель маршрутов',
    'badgeStorytellerDescription': 'Напишите 5 подробных отзывов',
    'badgeStorytellerTitle': 'Рассказчик',
    'badgeStyleSamplerDescription': 'Исследуйте 5 категорий путешествий',
    'badgeStyleSamplerTitle': 'Проба стилей',
    'badgeTagCuratorDescription': 'Добавьте теги к 10 отзывам',
    'badgeTagCuratorTitle': 'Куратор тегов',
    'badgeWeekendExplorerDescription': 'Посетите 3 места за один уикенд',
    'badgeWeekendExplorerTitle': 'Исследователь выходных',
    'levelCityScout': 'Городской разведчик',
    'levelLocalExpert': 'Локальный эксперт',
    'levelNewExplorer': 'Новый исследователь',
    'levelRouteBuilder': 'Создатель маршрутов',
    'levelTravelLegend': 'Легенда путешествий',
    'levelWeekendTraveler': 'Путешественник выходного дня',
    'levelWorldExplorer': 'Исследователь мира',
    'savedNotes': 'Сохраненные заметки',
    'savedRoute': 'Сохраненный маршрут',
    'savedRouteFallback': 'Сохраненный маршрут',
    'savedPlacesCount': 'Сохранено мест: {count}',
    'savePreferencesCount': 'Сохранить предпочтения: {count}',
    'search': 'Поиск',
    'searchFilters': 'Фильтры поиска',
    'searchHint': 'Искать места, города, достопримечательности...',
    'searchLocationHint': 'Искать город, аэропорт, станцию, адрес...',
    'searching': 'Ищем...',
    'settings': 'Настройки',
    'settingsSubtitle': 'Настройте Atlas под свой стиль путешествий.',
    'setupLater': 'или настройте позже.',
    'shareVisitDetails': 'Поделитесь деталями визита',
    'shopping': 'Шопинг',
    'showLess': 'Свернуть',
    'signIn': 'Войти',
    'slideToContinue': 'Проведите, чтобы продолжить',
    'splashHeadline': 'Некоторые места\nменяют нас\nнавсегда.',
    'splashSubtitle': 'Открывайте, планируйте и исследуйте с Atlas.',
    'startJourney': 'Начать путешествие!',
    'starRating': 'Звезд: {count}',
    'submitReview': 'Отправить отзыв',
    'support': 'Поддержка',
    'system': 'Системная',
    'switchToMapMode': 'Переключить на {label}',
    'tapToEditReview': 'Нажмите, чтобы отредактировать отзыв',
    'termsPrivacy': 'Условия / политика приватности',
    'termsPrivacyMessage':
        'Atlas хранит профиль, предпочтения, избранное, отзывы и поездки, чтобы давать рекомендации и синхронизировать активность. Добавьте финальный юридический текст или ссылки перед релизом.',
    'termsPrivacySubtitle': 'Читать условия и заметки о приватности',
    'theme': 'Тема',
    'touristAttractions': 'Достопримечательности',
    'trendingToday': 'Популярно сегодня в Atlas',
    'tripsPlannedCount': 'Запланировано поездок: {count}',
    'tripDeleted': 'Поездка удалена.',
    'tripSavedToPlannedTrips': 'Поездка сохранена в запланированные поездки.',
    'tryAnotherRoute':
        'Попробуйте другую точку старта, пункт назначения или проверьте покрытие API позже.',
    'tryMoreDetails':
        'Попробуйте название места, город или достопримечательность с чуть большей детализацией.',
    'updateReview': 'Обновить отзыв',
    'useFavorites': 'Использовать избранное',
    'useFavoritesSubtitle': 'Улучшать рекомендации по сохраненным местам',
    'useReviews': 'Использовать отзывы',
    'useReviewsSubtitle': 'Улучшать рекомендации по вашим оценкам',
    'username': 'Имя пользователя',
    'unnamedPlace': 'Место без названия',
    'usernameCannotBeEmpty': 'Имя пользователя не может быть пустым.',
    'welcomeBack': 'С возвращением!',
    'welcomeUser': 'Здравствуйте, {username}!',
    'youCanAlsoVisit': 'Можно также посетить',
    'youAreCurrentlyIn': 'Вы сейчас в',
    'yourFeedbackHelps': 'Ваш отзыв помогает другим путешественникам',
    'yourSelectedArea': 'выбранная область',
    'zoos': 'Зоопарки',
  },
};
